export const SET_INFO = 'SET_INFO'
export const SET_SYSTEM = 'SET_SYSTEM'
export const SET_TOPIC = 'SET_TOPIC'
export const SET_LOCATION = 'SET_LOCATION'
export const SET_WEBSOCKET = 'SET_WEBSOCKET'
export const SET_MSGNUMS = 'SET_MSGNUMS'